### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MiWeiss** [noameshed/novelty-detection#1]
Hi :-)

Would you mind adding a license? See [choosealicense.com](choosealicense.com) for software licenses and [CC-Choose](https://creativecommons.org/choose/) for datasets, artifacts, ...

Also, after adding a license - allowing people to use your repo content, you may want to consider describing on the readme how you want to be cited :-)

Would be highly appreciated.

**Comment by noameshed** [comment]
Thanks for bringing this up! I've added citation information to the README and added a license.
