### ISSUE TITLE
Add a new file for the ImageNet categories with labels and indexes

### ISSUE THREAD

**Issue by miguelCalado** [noameshed/novelty-detection#2]
Hi, 

Thank you for the great effort of annotating the ImageNet labels into categories. I think it is a great addition and found it very useful!

Nevertheless, I think the format of the ```imagenet_categories.csv``` is not very straightforward for someone that wants to use both the labels, synset and categories right out of the bat, and I even struggled a little bit with it. 

Would you mind adding another csv that contains all of this information (e.g. index, label, synset and category)?
Below I added my version of the above-mentioned file. Feel free to use it :)

Cheers.
[imagenet_categories_synset.csv](https://github.com/noameshed/novelty-detection/files/7167862/imagenet_categories_synset.csv)

**Comment by noameshed** [comment]
Hi @miguelCalado 

Apologies for the delay, it's been a busy time! I have committed your version which includes the synsets as well as the categories. Thanks for putting that together and sharing it!

Noam
