### ISSUE TITLE
How do you get the imagenet 1000subclass--67superclass map (imagenet_categories_synset.csv)?

### ISSUE THREAD

**Issue by Wangt-CN** [noameshed/novelty-detection#3]
Hi, Noam Eshed,

Thanks a lot for the provided imagenet class mapping file (from 1000 subclasses to 67 super classes). However, I wondered what is the reference file to get this mapping? I tried the imagenet wordnet tree, but it seemed that it cannot get 67 classes.

Best,
Tan

**Comment by noameshed** [comment]
Hi @Wangt-CN ,
I made the 67 super classes by hand, so it is not a direct result of the imagenet wordnet tree.

Best,
Noam
